name: Backend CI

on:
  push:
    branches: [main]
    paths:
      - "backend/**"

  pull_request:
    branches: [main]
    paths:
      - "backend/**"

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 25
          working-directory: ./backend

      - name: Install dependencies
        run: npm ci
        working-directory: ./backend

      - name: Run tests
        run: npm run test
        working-directory: ./backend
